# -*- coding: utf-8 -*-
"""backup_manager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sr0drRERU9-R2DzIgbWDaX-jAe26bRWf
"""

from pathlib import Path
import shutil
import sys
from datetime import datetime

def main():
    # Read command-line arguments
    if len(sys.argv) != 3:
        print("Usage: python backup_manager.py <source_directory> <backup_directory>")
        return

    source_directory = Path(sys.argv[1])
    backup_directory = Path(sys.argv[2])

    # Create backup directory if it does not exist
    backup_directory.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    log_file = Path("backup_log.txt")

    with open(log_file, "a") as log:

        for file in source_directory.iterdir():

            if file.is_file() and file.suffix in [".csv", ".json"]:

                backup_name = f"{file.stem}_{timestamp}{file.suffix}"
                backup_path = backup_directory / backup_name

                # Copy file
                shutil.copy2(file, backup_path)

                log.write(f"{datetime.now()} - Copied {file.name} to {backup_name}\n")

                # Find all backups of this file
                backups = sorted(
                    backup_directory.glob(f"{file.stem}_*{file.suffix}"),
                    key=lambda x: x.stat().st_mtime,
                    reverse=True
                )

                # Keep only the latest 5 backups
                if len(backups) > 5:
                    for old_backup in backups[5:]:
                        old_backup.unlink()
                        log.write(f"{datetime.now()} - Deleted old backup {old_backup.name}\n")


if __name__ == "__main__":
    main()

