# -*- coding: utf-8 -*-
"""Multi-Source Data Merger.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17yBNau2wqeeWWsCvyf7Ni-AJzC5Fk5R2
"""

from pathlib import Path
import csv
import json
from datetime import datetime

# Locate CSV files automatically
data_path = Path(".")
csv_files = list(data_path.glob("data*.csv"))

all_rows = []

# Read data from each CSV file
for file in csv_files:
    with open(file, "r", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            all_rows.append(row)

# Remove duplicate rows
unique_set = set()
unique_rows = []

for row in all_rows:
    key = (row["date"], row["product"], row["qty"], row["price"])
    if key not in unique_set:
        unique_set.add(key)
        unique_rows.append(row)

# Sort rows by date
unique_rows.sort(key=lambda x: x["date"])

# Calculate revenue per product
revenue_by_product = {}

for row in unique_rows:
    product = row["product"]
    qty = int(row["qty"])
    price = float(row["price"])
    revenue = qty * price

    if product not in revenue_by_product:
        revenue_by_product[product] = 0

    revenue_by_product[product] += revenue

# Calculate total revenue
total_revenue = sum(revenue_by_product.values())

# Export merged_sales.csv
with open("merged_sales.csv", "w", newline="") as f:
    fieldnames = ["date", "product", "qty", "price"]
    writer = csv.DictWriter(f, fieldnames=fieldnames)

    writer.writeheader()
    writer.writerows(unique_rows)

# Prepare JSON output
output = {
    "metadata": {
        "files_processed": len(csv_files),
        "total_rows": len(unique_rows),
        "total_revenue": total_revenue,
        "generated_at": datetime.now().isoformat()
    },
    "revenue_by_product": revenue_by_product
}

# Export revenue_summary.json
with open("revenue_summary.json", "w") as f:
    json.dump(output, f, indent=2)